import { Page, Panel } from '../components/Layout'
import { StatusBadge } from '../components/StatusBadge'
import { UlpinPanel } from '../components/UlpinPanel'
import { useDataset } from '../services/datasetContext'
import { navigate } from '../services/router'
import { useSelection } from '../services/selectionContext'

export function UlpinPage() {
  const { ulpins } = useDataset()
  const selection = useSelection()
  const record = ulpins.records.find((r) => r.unitId === selection.unitId) ?? ulpins.records[0]

  return (
    <Page
      eyebrow="Identifier register"
      title="Prototype 3D ULPIN"
      lede={ulpins.disclaimer}
      aside={<StatusBadge tone="prototype" label={`Scheme ${ulpins.scheme}`} />}
    >
      <div className="split split--ulpin">
        <Panel title={`${ulpins.count} identifiers`}>
          <ul className="ulpin-list">
            {ulpins.records.map((r) => (
              <li key={r.code}>
                <button type="button" className={record && r.code === record.code ? 'is-active' : ''} onClick={() => selection.selectUnit(r.unitId)}>
                  <code>{r.code}</code>
                  <span>{r.unitId} · {r.storeyNames.join(', ')}</span>
                </button>
              </li>
            ))}
          </ul>
        </Panel>
        {record ? (
          <Panel
            title="Identifier record"
            action={<button type="button" className="btn btn--sm" onClick={() => { selection.selectUnit(record.unitId); navigate('viewer') }}>View unit in 3D</button>}
          >
            <UlpinPanel record={record} detailed />
            <div className="identity">
              <span className="eyebrow">Identity fields hashed into the identifier</span>
              <pre className="mono">{JSON.stringify({
                scheme: record.scheme,
                dataset: record.dataset,
                parcel_id: record.parcelId,
                building_id: record.buildingId,
                property_unit_id: record.unitId,
                storey_ids: record.storeyIds,
                vertical_extent_m: record.verticalExtentM,
                geometry_version: record.geometryVersion,
                source_ids: `[${record.sourceIds.length} IfcSpace GlobalIds]`,
              }, null, 2)}</pre>
              <p className="note">The identifier changes when any of these fields changes, including the geometry version. It is generated by this demonstrator and is not issued by any authority.</p>
            </div>
          </Panel>
        ) : (
          <Panel><p className="note">ulpins.json contains no records.</p></Panel>
        )}
      </div>
    </Page>
  )
}
